apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cseb-mid-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PaviTechDevloper/CSEB_MID.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: cseb-mid-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true