apiVersion: v1
kind: Service
metadata:
  name: skillexchange-app-preview
  namespace: cseb-mid-ns
spec:
  selector:
    app: skillexchange-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort